modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved."
issueTrackerURL="https://github.com/RaveTr/Villagery/issues"

[[mods]]
modId="villagery"
version="${file.jarVersion}"
displayName="Villagery"
updateJSONURL="https://raw.githubusercontent.com/RaveTr/Villagery/forge-1.19.3/updates.json" 
#displayURL="" 
logoFile="examplemod.png" 
credits="MnK"
authors="Meme Man, Donkoki"
displayTest="MATCH_VERSION"
#configBackground="villagery:textures/"
description='''Overhauls villages and adds new village-related content to the game, breathing more life into the villager universe.'''

[[dependencies.villagery]] 
    modId="forge" 
    mandatory=true 
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="geckolib" 
    mandatory=true 
    versionRange="[4.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="smartbrainlib" 
    mandatory=true 
    versionRange="[1.7.3,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.villagery]] 
    modId="roughlyenoughitems" 
    mandatory=false
    versionRange="[10.0.581,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="roughlyenoughresources" 
    mandatory=false
    versionRange="[2.5.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.villagery]] 
    modId="clothconfig" 
    mandatory=false
    versionRange="[9.0.94,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.villagery]] 
    modId="architectury" 
    mandatory=false
    versionRange="[7.0.66,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.villagery]] 
    modId="configured" 
    mandatory=false
    versionRange="[2.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="catalogue" 
    mandatory=false
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="jade" 
    mandatory=false
    versionRange="[9.2.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="theoneprobe" 
    mandatory=false
    versionRange="[1.19.3-7.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagery]] 
    modId="appleskin" 
    mandatory=false
    versionRange="[2.4.2,)"
    ordering="NONE"
    side="BOTH"